### ISSUE TITLE
Request for Collaborator Access

### ISSUE THREAD

**Issue by Tickwy** [wesk-fr/we_rig_showcase#1]
## Personal Information

- **Name**: Alexis
- **Email**: coppeealexis@gmail.com 
- **GitHub Username**: Tickwy
- **Organization/Company** (if applicable): Illumination
- **Reason for Access Request**:

### Additional Information/Message
Please provide any other information or context regarding why you're seeking access to the main repository.
or None.

**Comment by wesk-fr** [comment]
Welcome Tickwy !
