### ISSUE TITLE
Request for Collaborator Access

### ISSUE THREAD

**Issue by michelsatish** [wesk-fr/we_rig_showcase#2]
## Personal Information

- **Name**: sathish
- **Email**: michelsatishss@gmail.com
- **GitHub Username**: michelsatish
- **Organization/Company** (if applicable): freelancer
- **Reason for Access Request**: it would be helpful for freelancer like me to understand tools 

### Additional Information/Message
Please provide any other information or context regarding why you're seeking access to the main repository.
or None.

**Comment by wesk-fr** [comment]
Request Accepted.

"Reason for Access Request: it would be helpful for freelancer like me to understand tools"

Nice to hear :)
But i've to say. Pretty much every docstrings are written in french.
And, there isnt any comment...

I'll do my best to update all of this so you can get a better understanding of everything.

Best,

Math

**Comment by wesk-fr** [comment]
Request Accepted.

"Reason for Access Request: it would be helpful for freelancer like me to understand tools"

Nice to hear :)
But i've to say. Pretty much every docstrings are written in french.
And, there isnt any comment...

I'll do my best to update all of this so you can get a better understanding of everything.

Best,

Math

**Comment by michelsatish** [comment]
page not found gotta an error
________________________________

**Comment by michelsatish** [comment]
now tools are showing thank you
________________________________
